server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/  #当前注册中心的访问地址
  instance:
    prefer-ip-address: true #是否将当前服务的ip注册到EurekaServler
    ip-address: 127.0.0.1
spring:
  application:
    name: consumer  #当前服务在注册中心上的名称



